### ISSUE TITLE
Error parsing logs with no valid timestamps for tail command

### ISSUE THREAD

**Issue by heyjcollins** [vmware-tanzu/apps-cli-plugin#31] opened 2022-03-17 20:03 UTC
### Please fill out the issue checklist below and provide ALL the requested information.

- [X] I reviewed open and closed Github issues that may be related to my problem.
- [X] I am reporting a bug that others will be able to reproduce.

### Describe the bug
The cli attempts to parse the time stamp coming from the k8s api in the logs so that it can print the time in user's timezone. K8s returns time stamps inline with the log output as a prefix for each line. CLI prints error “unable”  when log line is not regular log output but is being interpreted as a log line. 

### Expected behavior
Consider not parsing the log line for these special logs. 

### Steps to Reproduce
Have any application that logs without timestamps as part of the app logs. Example errors reported from customer using sample `tanzu java web app`.

### Snippet
```
unexpected error: parsing time "unable" as "2006-01-02T15:04:05.999999999Z07:00": cannot parse "unable" as "2006"
unexpected error: parsing time "rpc" as "2006-01-02T15:04:05.999999999Z07:00": cannot parse "rpc" as "2006"
```

### Version (Apps plugin version, Version of K8s running on cluster)
Put the output of the following commad
Apps plugin `v0.4.0`+ 

### Additional context & Relevant Debug Output (Logs, etc)
Issue originally submitted by @shashwathi

**Comment by heyjcollins** [comment] 2022-03-17 20:04
comment originally submitted by @ordinnordico

`stern` library is generating that error whenever the `timestamp` flag is set to true, this is an open discussion in `stern` repo: [161](https://github.com/stern/stern/issues/161 )

**Comment by shaheerkootteeri** [comment] 2022-11-17 20:08
I am able to validate that the unable to parse error on tanzu apps cli has been fixed as part of the latest version of stern ( 1.22.0 ) .

**Root cause of the issue** :- 

As mentioned on the Pull request https://github.com/stern/stern/pull/178/ the issue is when stern error try to parse a string as timestamp, stern was returning error ( parse exception) back and the logs were ignored. The PR -178 fixes the issue.

Issue reproduced in V0.9.0 of apps-cli , stern V1.21.0
<img width="107" alt="image" src="https://user-images.githubusercontent.com/108013945/202548208-fad21b44-3657-4560-95e1-4b3347a2048e.png">

![image](https://user-images.githubusercontent.com/108013945/202548349-7dfc8652-ef19-4992-8170-3a1c884c688b.png)


After updating the tanzu cli version with the latest - stern version V1.22.0

<img width="1189" alt="image" src="https://user-images.githubusercontent.com/108013945/202548676-896a25d4-b50d-4f1b-996c-8b5fcfb4866a.png">

**Comment by atmandhol** [comment] 2022-11-18 15:40
Stern upgrade was done as part of this PR: https://github.com/vmware-tanzu/apps-cli-plugin/pull/400. Closing this as we cannot reproduce this issue after stern upgrade.

**Closed by atmandhol** 2022-11-18 15:40 UTC
Labels: bug, accepted
